### ISSUE TITLE
License

### ISSUE THREAD

**Issue by papb** [jordyv/wait-for-healthy-container#1]
Hello, can you please add a license to this project? If you're not familiar with any, I suggest the MIT license, which is very permissive and has a very short text. Thanks!

**Comment by jordyv** [comment]
Hi @papb,
Thanks for the suggestion! I added the MIT license file to the project.

**Comment by papb** [comment]
Thank you very much!!

**Comment by oregonpillow** [comment]
@jordyv found this script today. Works great for my needs. Nice one!
