### ISSUE TITLE
wait-for-healthy-container.sh: line 26 

### ISSUE THREAD

**Issue by megamayoy** [jordyv/wait-for-healthy-container#2]
I use this scrip as an entry point for a Docker container so I run it in the **Dockerfile** of the project like this 
`ENTRYPOINT ["./cmd/wait-for-healthy-container.sh", "mysql_db", "120"]`

Every time the script runs, it give me this error `./cmd/wait-for-healthy-container.sh: line 26: docker: command not found
` it points to this line `state=$(docker inspect -f '{{ .State.Health.Status }}' ${container_name})` where the status is checked

any help?

**Comment by joebowbeer** [comment]
The container is waiting on its own good health? That's not going to work. Generally the orchestrator should handle health concerns.

But, that aside, if you need docker in your path then your Dockerfile needs to install it, or extend a base that already has it installed.
